### ISSUE TITLE
State level statistics

### ISSUE THREAD

**Issue by eavaught** [xyshal/counties#1]
I want to see state level statistics including % of states visited, and % counties visited in each state.

**Comment by xyshal** [comment]
This feature was completed in 29238bea44d4e863f7c158c5d76643c41d8b1bc2

**Comment by eavaught** [comment]
Still missing % of states visited.

**Comment by xyshal** [comment]
I’m sorry, is the application called qstates???

**Comment by xyshal** [comment]
Added states visited stats in f8f21d5a56d80d9b3b6ab8280b6cf4ad9328f1f2
