### ISSUE TITLE
Trailing commas in CSV file does not open correctly

### ISSUE THREAD

**Issue by eavaught** [xyshal/counties#2]
Saving CSV's with excel adds trailing commas. I would expect files that have been edited in excel to work.

<details><summary>Console Error Messages</summary>

![image](https://user-images.githubusercontent.com/14095837/146091876-017fd4f0-e2f9-443a-b6a7-549c9e747edd.png)

</details>

**Comment by xyshal** [comment]
Hm, maybe we should pull in a CSV parsing library.

**Comment by xyshal** [comment]
Resolved in 50f1d5fff493ad6ea2cd92ae21e171c6b7b606b4
